name: build addon
  
on:
  push:
    tags: ["*"]
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo -e "pre-commit\nscons\nmarkdown" > requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Code checks
        run: |
          export SKIP=no-commit-to-branch
          pre-commit run --all

      - name: Building addon
        run: |
          scons pot
            scons

      - name: List built files
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged_addon
          path: |
            ./*.nvda-addon
            ./*.pot

  upload_release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
      - uses: actions/checkout@v4

      - name: Download releases files
        uses: actions/download-artifact@v4
        with:
          name: packaged_addon

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*.nvda-addon
            ./*.pot
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref, '-') }}
